spring:
  datasource:
    name: stock data  #数据库名
    url: jdbc:mysql://localhost:3306/stock data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root  #用户名
    password: 120019  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动

mybatis:
    mapper-locations: classpath:mapper/StockMapper.xml  #配置映射文件

server:
  port: 8081